### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AshishGusain17** [TannerGilbert/Model-Interpretation#1]
__init__() got multiple values for argument 'class_index'
Hey, this is the error I am getting now

**Comment by TannerGilbert** [comment]
Can you send me the your code?

**Comment by AshishGusain17** [comment]
I actually tried your code and  got the error.
I  am getting some different error in my code, so I tried yours.


This is my notebook which has error:
https://colab.research.google.com/drive/1YA85K38jNYtG4t3O3oLjUEirb9N07Zw_

**Comment by AshishGusain17** [comment]
![Screenshot (313)](https://user-images.githubusercontent.com/57452568/84372760-3acde580-abf9-11ea-80e2-deb52d715cf4.png)
This is the error in your code

**Comment by TannerGilbert** [comment]
I just checked the code and it seems like the GradCAMCallback has changed.

Replace:
```
tf_explain.callbacks.GradCAMCallback(validation_class_zero, 'target_layer', class_index=0),
tf_explain.callbacks.GradCAMCallback(validation_class_fours, 'target_layer', class_index=4),
```

with

```
tf_explain.callbacks.GradCAMCallback(validation_class_zero, layer_name='target_layer', class_index=0),
tf_explain.callbacks.GradCAMCallback(validation_class_fours, layer_name='target_layer', class_index=4),
```

**Comment by AshishGusain17** [comment]
thnx....now it works
