### ISSUE TITLE
regarding target layer name

### ISSUE THREAD

**Issue by AshishGusain17** [TannerGilbert/Model-Interpretation#2]
Hey,
While we are using layers_name=["target_layer"], this target layer is added by you. Now if I am using some pretrained model like ResNet50 and use the layer name of one of its layer, how to use it. Right now I am getting error

**Comment by TannerGilbert** [comment]
Can you send me the error message?

**Comment by AshishGusain17** [comment]
I used block4_conv1 as layer_name which is a  layer in VGG16.
Getting errors in all the layer names of any model that are present already. If I add my convolutional layer, it works. 
![Screenshot (336)](https://user-images.githubusercontent.com/57452568/84810208-a2849600-b028-11ea-9e0c-3d998b11a903.png)

**Comment by TannerGilbert** [comment]
What version of Tensorflow are you using?

**Comment by AshishGusain17** [comment]
tf 2.0 and it is working comfortably with tf-explain.
But if I use transfer learning and provide name of initial layers,I get error
